% run from main ripples directory



subs={'s01', 's02', 's03', 's04', 's05', 's06',};
for s=1:6
    sub = subs{s};
    data_path = ['/Users/jthompson/data/ripples/', sub, filesep];
    if strcmp(sub, 's01')
		% ABBA 8 runs
		bases = {['ripples_', sub, '_run1_simple'], ['ripples_', sub, ...
            '_run2_combo'], ['ripples_', sub, '_run3_combo'], ...
            ['ripples_', sub, '_run4_simple'], ['ripples_', sub, ...
            '_run5_simple'], ['ripples_', sub, '_run6_combo'], ...
            ['ripples_', sub, '_run7_combo'], ['ripples_', sub, ...
            '_run8_simple']};
    elseif strcmp(sub, 's02') || strcmp(sub, 's03')
		% ABBA 12 runs
		bases = {['ripples_', sub, '_run1_simple'], ['ripples_', sub, ...
            '_run2_combo'], ['ripples_', sub, '_run3_combo'], ...
            ['ripples_', sub, '_run4_simple'], ['ripples_', sub, ...
            '_run5_simple', ['ripples_', sub, '_run6_combo'], ...
            ['ripples_', sub, '_run7_combo'], ['ripples_', sub, ...
            '_run8_simple'], ['ripples_', sub, '_run9_simple'], ...
            'ripples_'+ sub, '_run10_combo'], ['ripples_'+ sub, ...
            '_run11_combo'], ['ripples_'+ sub, '_run12_simple']};
    else
        % BAAB 12 runs
		bases = {['ripples_', sub, '_run1_combo'], ['ripples_', sub, ...
            '_run2_simple'], ['ripples_', sub, '_run3_simple'], ...
            ['ripples_', sub, '_run4_combo'], ['ripples_', sub, ...
            '_run5_combo'], ['ripples_', sub, '_run6_simple'], ...
            ['ripples_', sub, '_run7_simple'], ['ripples_', sub, ...
            '_run8_combo'], ['ripples_', sub, '_run9_combo'], ...
            ['ripples_', sub, '_run10_simple'], ['ripples_', sub, ...
            '_run11_simple'], ['ripples_', sub, '_run12_combo']};
    end

    % Make cell array of vtc file names
    smooth = '_SD3DVSS6.00mm';
    if strcmp(sub, 's01')
        for r=1:8
            VTCs{r} = [data_path, bases{r}, ...
                '_SCSTBL_3DMCS_THPGLMF6c_b02b0_TU_TAL', smooth, '.vtc'];
        end
    else
        for r=1:12
            VTCs{r} = [data_path, bases{r}, ...
                '_SCSTBL_3DMCS_LTR_THPGLMF6c_b02b0_TU_TAL', smooth, ...
                '.vtc'];
        end
    end

    % Make cell array of .sdms file names
    fname = ['_minus', '_scaled', '_cHRF', '+MC'];
    sprintf('%s%s_run%d_%s_RippleIndicator%dD%s.sdm',sdmdir, ...
            sub, run, runtype, nfeatures, fname);
    
    % Save .mdm 
end
    



for s=1:6
    sub=subs{s};
    if s==1
        bigmdm = xff([sub filesep 'mdms' filesep sprintf('%s_RI4D-MINUS+SoundOn_scaled+MC_smth2mm.mdm', sub)]);
    else
        mdm=xff([sub filesep 'mdms' filesep sprintf('%s_RI4D-MINUS+SoundOn_scaled+MC_smth2mm.mdm', sub)]);
        bigmdm.XTC_RTC = cat(1, bigmdm.XTC_RTC, mdm.XTC_RTC);
    end
end

bigmdm.SaveAs('RI4D-MINUS+SoundOn_scaled+MC_smth2mm_allsubs.mdm')